EWallet.web/Controllers/CategoryController.cs
using EWallet.bl;
using EWallet.viewModels;
using System.Web.Mvc;

namespace EWallet.web.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private ICategoryService _categoryService;

        public CategoryController(CategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // GET: Category
        public ActionResult Index(int type)
        {
            var result = _categoryService.GetCategories(type == 0 ? data.OperationType.Income : data.OperationType.Spending, User);
                                                                            
            ViewBag.Type = type;

            return View(result);
        }

        [HttpGet]
        public ActionResult Create(int type)
        {
            return View(new CategoryViewModel {
                                                CategoryType = type == 0 ? data.OperationType.Income : data.OperationType.Spending
                                            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryViewModel create)
        {
            _categoryService.CreateCategory(create, User);

            return RedirectToAction("Index", new { type=(int)create.CategoryType});
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(_categoryService.GetCategory(id, User));
        }

        [HttpPost]
        public ActionResult Edit(CategoryViewModel edit)
        {
            _categoryService.EditCategory(edit, User);

            return RedirectToAction("Index", new { type = (int)edit.CategoryType });
        }

        public ActionResult Delete(int id, int type)
        {
            var categoryType = type;
             
            _categoryService.DeleteCategory(id, User);

            return RedirectToAction("Index", new { type = categoryType });
        }
    }
}

EWallet.web/Controllers/DynamicsController.cs
using EWallet.bl;
using EWallet.viewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWallet.web.Controllers
{
    [Authorize]
    public class DynamicsController : Controller
    {
        private IDynamicsService _dynamicsService;

        public DynamicsController(IDynamicsService dynamicsService)
        {
            _dynamicsService = dynamicsService;
        }

        // GET: Dynamics
        public ActionResult Index()
        {
            return View(_dynamicsService.FillDictionaries(new DynamicsViewModel()));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChartData(DynamicsViewModel model)
        {
            if (model.ByCategories)
            {
                return Json(_dynamicsService.GetChartDataByCategories(model, User), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(_dynamicsService.GetChartDataByTypes(model, User), JsonRequestBehavior.AllowGet);
            }            
        }
    }
}

EWallet.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - E-Wallet</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("E-Wallet", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Операции", "Index", "Home")</li>
                    <li>@Html.ActionLink("Категории доходов", "Index", "Category", new { type = 0 }, null)</li>
                    <li>@Html.ActionLink("Категории расходов", "Index", "Category", new { type = 1 }, null)</li>
                    <li>@Html.ActionLink("Динамика изменения средств", "Index", "Dynamics")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - E-Wallet</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap") 
    @Scripts.Render("~/bundles/general")   
    @RenderSection("scripts", required: false)
</body>
</html>